// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vertigo.Data;

#nullable disable

namespace Vertigo.Migrations
{
    [DbContext(typeof(VertigoContext))]
    partial class VertigoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Vertigo.Models.Boutique", b =>
                {
                    b.Property<int>("IDBoutique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BAN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoutiqueImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdGerant")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int>("NBReport")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NBvente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomBoutique")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Valide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IDBoutique");

                    b.HasIndex("IdGerant");

                    b.ToTable("Boutique");
                });

            modelBuilder.Entity("Vertigo.Models.Commande", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDeCommande")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanierID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reduction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Statut")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("PanierID");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("Vertigo.Models.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PanierId");

                    b.HasIndex("UtilisateurId", "PanierId")
                        .IsUnique();

                    b.ToTable("Favoris");
                });

            modelBuilder.Entity("Vertigo.Models.Panier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdBoutique")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NBdispo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PanierImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PanierPrix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("IdBoutique");

                    b.ToTable("Panier");
                });

            modelBuilder.Entity("Vertigo.Models.RecurringSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoutiqueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFailureReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetDay")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TargetTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoutiqueId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Vertigo.Models.ReservationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppliedDiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReservedOfferId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Vertigo.Models.Utilisateur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BAN")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Etudiant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NBReport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumCarteEtu")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wilaya")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Vertigo.Models.Boutique", b =>
                {
                    b.HasOne("Vertigo.Models.Utilisateur", "Gerant")
                        .WithMany()
                        .HasForeignKey("IdGerant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vertigo.Models.Evaluation", "Note", b1 =>
                        {
                            b1.Property<int>("BoutiqueIDBoutique")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("NbNote")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Note")
                                .HasColumnType("REAL");

                            b1.HasKey("BoutiqueIDBoutique");

                            b1.ToTable("Boutique");

                            b1.WithOwner()
                                .HasForeignKey("BoutiqueIDBoutique");
                        });

                    b.Navigation("Gerant");

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("Vertigo.Models.Commande", b =>
                {
                    b.HasOne("Vertigo.Models.Utilisateur", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vertigo.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("PanierID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Panier");
                });

            modelBuilder.Entity("Vertigo.Models.Favori", b =>
                {
                    b.HasOne("Vertigo.Models.Panier", "Panier")
                        .WithMany()
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vertigo.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Vertigo.Models.Panier", b =>
                {
                    b.HasOne("Vertigo.Models.Boutique", "Boutique")
                        .WithMany()
                        .HasForeignKey("IdBoutique")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vertigo.Models.Evaluation", "Note", b1 =>
                        {
                            b1.Property<int>("PanierID")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("NbNote")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Note")
                                .HasColumnType("REAL");

                            b1.HasKey("PanierID");

                            b1.ToTable("Panier");

                            b1.WithOwner()
                                .HasForeignKey("PanierID");
                        });

                    b.Navigation("Boutique");

                    b.Navigation("Note")
                        .IsRequired();
                });

            modelBuilder.Entity("Vertigo.Models.RecurringSubscription", b =>
                {
                    b.HasOne("Vertigo.Models.Boutique", "Boutique")
                        .WithMany()
                        .HasForeignKey("BoutiqueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Vertigo.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Boutique");

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
